import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";

const merriweather = Merriweather({
  subsets: ["latin"], // Specify the character subsets you need
  weight: ["400", "700"], // Choose the weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${merriweather.className} antialiased`}>{children}</body>
    </html>
  );
}
