import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import localFont from "next/font/local";

import { Toaster } from "react-hot-toast";
import "./globals.css";

const merriweather = Merriweather({
  subsets: ["latin"], // Specify the character subsets you need
  weight: ["400", "700"], // Choose the weights you need
});

const GeistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "400 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${merriweather.className} text-sm ${GeistSans.variable} antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
